### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by aronprins** [alexander171294/web-poker#13]
Hey Alexander,

I've worked with the Nikitin team to have this design developed and created and obtained the copyrights from them.

Please let me know if you'd be interested in acquiring the full design and rights for your project :)

Cheers,
Aron

<img width="1175" alt="Screenshot 2019-10-23 at 15 09 24" src="https://user-images.githubusercontent.com/1126344/67396042-3770e580-f5a7-11e9-9e1c-5c0dbdf93a00.png">

<img width="1172" alt="Screenshot 2019-10-23 at 15 09 32" src="https://user-images.githubusercontent.com/1126344/67396043-38097c00-f5a7-11e9-9b6a-c0453518a189.png">

<img width="1212" alt="Screenshot 2019-10-23 at 15 09 54" src="https://user-images.githubusercontent.com/1126344/67396044-38097c00-f5a7-11e9-9cea-b4fce3f05d46.png">

<img width="1230" alt="Screenshot 2019-10-23 at 15 10 03" src="https://user-images.githubusercontent.com/1126344/67396045-38097c00-f5a7-11e9-98d6-d437736071a4.png">

**Comment by alexander171294** [comment]
:O nice, is a good design, but this project is open source and free, I don't have money for this, if you have problem with the use of this desing in this project and you own the right, then I redesign the frontend :(.

Ps: I send a pull request to your fork because is behind of main repo by 254 commits.

PPs: nice job converting the image to html/css 😮 

Regards.

**Comment by aronprins** [comment]
Hey Alex,

Are you on skype so we can talk? :)

Thanks,
Aron

**Comment by alexander171294** [comment]
Yes, my skype nickname is: alexander.eberle.171294

But I can't do a call, only chat plz.

Alexander Eberle.-
